trigger:
  branches:
    include:
      - main  # Update this to your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'  # Python version for any additional needs

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
  displayName: 'Set Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install virtualenv
  displayName: 'Upgrade pip and install virtualenv'

- script: |
    virtualenv venv
    source venv/bin/activate
    pip install PyPDF2 cryptography  # Install necessary libraries for PDF signing
    pip install pikepdf cryptography
    pip install pyhanko
    pip install pyOpenSSL
    pip install aspose-pdf
    pip install Spire.PDF



  displayName: 'Setup virtual environment and install dependencies'

- script: |
    source venv/bin/activate  # Activate the virtual environment
    python sign_pdf_embed.py input.pdf certificate.crt private.key "TerosonIsON0523!"  # Run the Python signing script
  displayName: 'Run PDF signing Python script'

- script: |
    echo "Files in the source directory:"
    ls $(Build.SourcesDirectory)
    echo "Files in the staging directory before copying:"
    ls $(Build.ArtifactStagingDirectory)
  displayName: 'List Files Before Copying'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'  # Source directory to copy from
    Contents: 'signed_output.pdf'  # Specify the signed PDF file explicitly
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Staging directory for artifacts
  displayName: 'Copy Signed PDFs to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path where signed PDFs are copied
    artifactName: 'SignedPDFs'  # Name of the artifact to publish
    publishLocation: 'Container'  # Publish location
  displayName: 'Publish Signed PDFs'
