trigger:
  branches:
    include:
      - main  # Update this to your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'  # Python version for any additional needs

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
  displayName: 'Set Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install virtualenv
  displayName: 'Upgrade pip and install virtualenv'

- script: |
    virtualenv venv
    source venv/bin/activate
    pip install pyopenssl cryptography
  displayName: 'Setup virtual environment and install dependencies'

- script: |
    chmod +x sign_pdf.sh
    ./sign_pdf.sh input.pdf path/to/certificate.crt path/to/private.key your_passphrase
  displayName: 'Run PDF signing Bash script'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.pdf'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Signed PDFs to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'SignedPDFs'
    publishLocation: 'Container'
  displayName: 'Publish Signed PDFs'
